# Generated by Django 4.0.2 on 2023-08-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
